catalogs:
  dev:
    '@oxc-node/core': ^0.0.27
    '@sxzz/eslint-config': ^7.0.1
    '@sxzz/prettier-config': ^2.2.1
    '@sxzz/test-utils': ^0.5.6
    '@types/debug': ^4.1.12
    '@types/node': ^22.15.21
    bumpp: ^10.1.1
    eslint: ^9.27.0
    prettier: ^3.5.3
    tsdown: ^0.12.2
    typescript: ~5.8.3
    unplugin-unused: ^0.5.0
    vitest: ^3.1.4

  prod:
    '@clack/prompts': ^0.11.0
    ansis: ^4.0.0
    cac: ^6.7.14
    debug: ^4.4.1
    diff: ^8.0.1
    giget: ^2.0.0
    rolldown: 1.0.0-beta.9-commit.51df2b7
ignoredBuiltDependencies:
  - rolldown
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
